version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  terraform: circleci/terraform@1.0.2
jobs:
  terrajob:
    executor: terraform/default
    steps:
      - checkout
      - run : terraform --version
      - run : export ${CONTEXT_ARM_CLIENT_SECRET} 
      - run : export ${CONTEXT_ARM_CLIENT_ID} 
      - run : export ${CONTEXT_ARM_SUBSCRIPTION_ID} 
      - run : export ${CONTEXT_ARM_TENANT_ID} 
      - run : cat /etc/os-release
      - run : printenv
      - terraform/init:
          path: .
      - terraform/validate:
          path: .
      - terraform/plan:
          path: .
      - terraform/apply:
          path: .    
    working_directory: ~/src
workflows:
  terrajob:
    jobs:
      - terrajob